name: CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions-bot@users.noreply.github.com"
        git config --global url."https://".insteadOf git://
        git config --global url."https://github.com/".insteadOf git@github.com:
    - name: Checkout ${GITHUB_SHA}
      uses: actions/checkout@v1
    - name: Install Zola
      run: sudo snap install --edge zola
    - name: Build ${GITHUB_SHA}
      run: zola build
    - name: Deploy ${GITHUB_SHA}.
      env:
        # Seems the token described in https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables doesn't work
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd public
        git init
        git submodule update --init --recursive
        git add .
        git commit -s -m "Deploy ${GITHUB_SHA}."
        git push --force "https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages